name: Deploy Airflow DAGs to MWAA

on:
  push:
    branches:
      - main
      - fix/aws-s3-sync-action

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "AWS_REGION"
        run: echo "$AWS_REGION"
      - name: "MWAA_ENV_NAME"
        run: echo "$MWAA_ENV_NAME"
      - name: "S3_BUCKET_NAME"
        run: echo "$S3_BUCKET_NAME"

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Sync DAGs to S3
      run: |
        aws s3 sync ./dags s3://${{ vars.S3_BUCKET_NAME }}/dags --region ${{ vars.AWS_REGION }}

    - name: Update MWAA Environment
      run: |
        aws mwaa update-environment --name ${{ vars.MWAA_ENV_NAME }} --region ${{ vars.AWS_REGION }} --dag-s3-path "dags/"
