name: Deploy Airflow DAGs to MWAA

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Sync DAGs to S3
      run: |
        aws s3 sync ./dags s3://${{ vars.S3_BUCKET_NAME }}/dags --region ${{ vars.AWS_REGION }}

    - name: Wait for MWAA environment to be ready
      run: |
        while true; do
          status=$(aws mwaa get-environment --name ${{ vars.MWAA_ENV_NAME }} --region ${{ vars.AWS_REGION }} --query 'Environment.Status' --output text)
          echo "Current status: $status"
          if [[ "$status" != "UPDATING" ]]; then
            break
          fi
          echo "Waiting for MWAA environment to finish updating..."
          sleep 30  # Wait for 30 seconds before checking again
        done

    - name: Update MWAA Environment
      run: |
        for i in {1..5}; do
          aws mwaa update-environment --name ${{ vars.MWAA_ENV_NAME }} --region ${{ vars.AWS_REGION }} --dag-s3-path "dags"
        done
