name: Deploy SAM Application

on:
  push:
    branches:
      - main  # Trigger on push to main branch
      - feature/kafka-producer-consumer
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      secrets: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install AWS CLI
        run: |
          pip install awscli aws-sam-cli

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install dependencies for Twitter and Reddit Producers
        run: |
          pip install -r kafka/src/twitter_producer/requirements.txt
          pip install -r kafka/src/reddit_producer/requirements.txt

      - name: Build SAM Application
        run: |
          cd kafka
          sam build

      - name: Deploy SAM Application
        run: |
          cd kafka
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name streamforge-sam --s3-bucket ${{ vars.S3_BUCKET_NAME }}

      - name: Verify Deployment
        run: |
          aws cloudformation describe-stacks --stack-name streamforge-sam
